### ISSUE TITLE
reset key()

### ISSUE THREAD

**Issue by ukcroupier** [dmsc/fastbasic#13]
The key() function returns the last key press but how do you reset it?  How do you know if a key has been pressed once or multiple times?

**Comment by dmsc** [comment]
Hi!

> The key() function returns the last key press but how do you reset it? How do you know if a key has been pressed once or multiple times?

You have two options:
- Read the key, with "GET". This will work with any full key, but not with keys that don't have an ATASCI code (like CONTROL-4, or CONTROL-SHIFT-S)
- Reset the location with the current key, with "POKE $2FC,255".

This program will show you the KEY() codes and ATASCI codes:
```
print "Press any key, ends with ESC"
repeat

  repeat : until key()
  print "Key code: "; key()
  get k
  print "ATASCI code: "; k

until k = 27

print "Ok!"
```

**Comment by ukcroupier** [comment]
I guess it's all there in the docs but I just didn't put it together.  I totally missed the part about GET var, I thought it was just GET #iochn, var, for reading files.

Thanks
