### ISSUE TITLE
can't compile master branch

### ISSUE THREAD

**Issue by rpolasek** [dmsc/fastbasic#2]
$ make
cl65 -g -tatari -Ccompiler/fastbasic.cfg --asm-define FASTBASIC_FP --asm-include-dir gen/fp -c -l obj/fp/actions.lst -o obj/fp/actions.o src/actions.asm
cl65: Don't know what to do with `obj/fp/actions.lst'
make: *** [Makefile:212: obj/fp/actions.o] Error 1

**Comment by dmsc** [comment]
Hi!
I think you are not using a current version of CC65, you need the one available over http://cc65.github.io/cc65/ . Please paste the result of `cl65 --version`

**Comment by dmsc** [comment]
Hi @rpolasek !
Any news with this?

**Comment by rpolasek** [comment]
i'm using cc65 v 2.13.3 because my package which should compile it based on git still doesn't work properly and cc65 is not i gentoo portage. unfortunately, i haven't found better ebuild yet.

**Comment by dmsc** [comment]
Hi,
The "-l" option to ca65 and cl65 was changed in https://github.com/cc65/cc65/commit/a6389e6406d804f7893ec5dd3b3f527fdef8b25d , about 7 years ago, before version 2.13.3, so your version must be some pre-release, and extremely old!

¿can't you simply download the 2.16 release from https://github.com/cc65/cc65/releases/tag/V2.16 and compile? Here it's a simple:

```
~$ mkdir src; cd src
~/src$ wget https://github.com/cc65/cc65/archive/V2.16.tar.gz
~/src$ tar xf V2.16.tar.gz 
~/src$ cd cc65-2.16/
~/src/cc65-2.16$ make prefix=/opt/cc65 install
```
I don't use Gentoo, but I think this ebuild should work: https://gpo.zugaina.org/dev-embedded/cc65
```
# $Header: $

EAPI="2"

inherit eutils toolchain-funcs multilib

DESCRIPTION="complete cross development package for 65(C)02 systems"
HOMEPAGE="https://cc65.github.io/cc65/"
SRC_URI="https://github.com/cc65/${PN}/archive/V${PV}.tar.gz -> ${P}.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="doc"

DEPEND="doc? ( app-text/linuxdoc-tools )"
RDEPEND=""

src_compile() {
	emake
	use doc && emake -C doc 
}

src_install() {
	prefix=/usr DESTDIR=${D} emake install
}
```

**Comment by rpolasek** [comment]
hello. i've just tried to build it using cc65 v2.16 and i can confirm it works ok. thanks for your support :-)

**Comment by dmsc** [comment]
Good, closing then.
