### ISSUE TITLE
Makefile c++ standard

### ISSUE THREAD

**Issue by Wrathchild70** [dmsc/fastbasic#20]
I found I needed to add the OPTFLAGS the setting -std=c++14 for a build under cygwin to work, although this is an older installation of gcc 5.3.0

**Comment by dmsc** [comment]
Hi!

> I found I needed to add the OPTFLAGS the setting -std=c++14 for a build under cygwin to work, although this is an older installation of gcc 5.3.0

It is good to know that adding "-std=c++14" option works in GCC 5, but IMHO I think that upgrading your GCC is the best option.

Yes, I currently build the windows version with GCC 8.3,  the Linux version with GCC 9.2 and the OSX version with GCC 6.1, all those versions default to C++14 standard.

Currently, the make-release script sets OPTFLAGS to "-DNDEBUG -Os -Wall -flto -flto-partition=none -static-libstdc++ -static-libgcc -Wl,--gc-sections" , those flags produce a small optimized binary.
