### ISSUE TITLE
bug in data word statement? Negative values not allowed.

### ISSUE THREAD

**Issue by jeffpiep** [dmsc/fastbasic#3]
The following produces a compilation error using release 3.6 in Windows 10:

`data test() WORD = 1,0,-1,0,1`

results in 
`parse error, expected: data word`
`data test() WORD = 1,0,<--- HERE -->-1,0,1`

I have to remove the negative value to successfully compile.

**Comment by dmsc** [comment]
Hi!

In current (git master) version, should be fixed.

Please, try attached version:

[fastbasic-v4.0-rc-win32.zip](https://github.com/dmsc/fastbasic/files/2873478/fastbasic-v4.0-rc-win32.zip)

[fastbasic-v4.0-rc.atr.zip](https://github.com/dmsc/fastbasic/files/2873479/fastbasic-v4.0-rc.atr.zip)

**Comment by jeffpiep** [comment]
That works. Thanks for the fast response - now back to the 10liners contest.
