### ISSUE TITLE
Error compiling data for string array. 

### ISSUE THREAD

**Issue by peteym5** [dmsc/fastbasic#32]
I am getting "expected: data type" error between the () and BYTE. I am following what is stated in the documentation. 

DATA GAME_OPTION_SHOW() BYTE = "          PLAY FOR HIGH SCORE       ",               
                        BYTE = "          WIPE OUT 25 LINES         ",
                        BYTE = "      NEW SCREEN FOR EVERY LEVEL    ",
                        BYTE = "  WIPEOUT MORE LINES FOR NEW LEVEL  ",
                        BYTE = "          WIPE OUT 50 LINES         ",
                        BYTE = "          WIPE OUT 100 LINES        ",
                        BYTE = "   PLAY FOR HIGH SCORE WITH HIGHT   "

**Comment by dmsc** [comment]
Hi!

What version are you using, and it is the IDE or the compiler?

Here, this works:
```
DATA GAME_OPTION_SHOW() BYTE = " PLAY FOR HIGH SCORE ",
DATA BYTE = " WIPE OUT 25 LINES ",
DATA BYTE = " NEW SCREEN FOR EVERY LEVEL ",
DATA BYTE = " WIPEOUT MORE LINES FOR NEW LEVEL ",
DATA BYTE = " WIPE OUT 50 LINES ",
DATA BYTE = " WIPE OUT 100 LINES ",
DATA BYTE = " PLAY FOR HIGH SCORE WITH HIGHT "
```

**Comment by dmsc** [comment]
Hi again, @peteym5 

Any update on this?
