### ISSUE TITLE
Windows 10 FB generates "The system cannot find the path specified."

### ISSUE THREAD

**Issue by peteym5** [dmsc/fastbasic#35]
I have been trying to Google search this issue. I am trying to like a Fast Basic program to some assembly code using FB (programnam.bas) (assembly.asm) at command prompt. I keep getting this error "The system cannot find the path specified." Using Windows 10.

**Comment by dmsc** [comment]
Hi!

> I have been trying to Google search this issue. I am trying to like a Fast Basic program to some assembly code using FB (programnam.bas) (assembly.asm) at command prompt. I keep getting this error "The system cannot find the path specified." Using Windows 10.

Please, use the last beta release to see if this issue is already fixed.

You need to be sure to specify the full paths to the ".bas" and the ".asm" files, best is to have both in the same folder.

You can attach a screenshot of the command window to see if I can figure out the reason for the error.

Thanks!

**Comment by peteym5** [comment]
I got it to compile. It may not work if there are spaces in folder or file names. Possible it needs to work only from C drive.

**Comment by dmsc** [comment]
Hi!

> I got it to compile. It may not work if there are spaces in folder or file names. Possible it needs to work only from C drive.

Great that you got it working, but it should work on paths with spaces and also in any drive, so if it does not work it is a bug.

Do you have your complete failing command line, so I can check?. As I don't use windows, I can miss problems with the tools there.

Thanks.

**Comment by dmsc** [comment]
Closing, as there were no further replies.
