### ISSUE TITLE
Compiler crashes with "Abort trap: 6" when source file has any errors (Mac)

### ISSUE THREAD

**Issue by billyc** [dmsc/fastbasic#44]
I am having a problem where any error, in even the smallest of test programs, crashes the FB compiler. This is using the prebuilt 4.5.2 binary for Mac, on an Intel Mac running 10.14 (Catalina) and also on an arm (m1) mac running 10.15 (Big Sur).

Pretty much any error in the code will trigger the crash in both the int and fp compilers, for example:

```
Graphics 5
z=5 boop
```

On Mac, I get the following output:
```
% fastbasic-int test.bas test.asm
Abort trap: 6
```

I don't experience this problem on a Windows 10 machine . On Windows I get the expected error:
```
test.bas:2:5: parse error, expected: '&', '!', 'EXOR', '*', '/', 'MOD', '+', '-', 'OR', 'AND', integer comparison operator
z=5 <--- HERE -->z
```

Am I doing something dumb? (Probably yes). I suspect this has more to do with permissions lockdown on Mac than on the fastbasic code. Sigh.

If there is anything I can do to help troubleshoot, debug, solve the problem, please let me know!

Debug output from `fastbasic-int -d` attached, in case that is any help!

Cheers

..b

[error.log](https://github.com/dmsc/fastbasic/files/6251065/error.log)

**Comment by dmsc** [comment]
Hi @billyc 

Please, test the attached binaries on OSX, one is for AMD64 mac, the other for ARM64 mac.

I updated my cross-build environment to the OSX11 SDK, and used current CLANG compiler. I don't like using CLANG much, as it is slower and produces bigger binaries than GCC, but seems better supported on OSX:

[fastbasic-4.5.3~test.osx11_ARM64.zip](https://github.com/dmsc/fastbasic/files/6253294/fastbasic-4.5.3.test.osx11_ARM64.zip)
[fastbasic-4.5.3~test.osx11.zip](https://github.com/dmsc/fastbasic/files/6253295/fastbasic-4.5.3.test.osx11.zip)

**Comment by billyc** [comment]
**amd64:** works perfectly on intel, 10.14 (catalina) machine! ✅ 

**arm64:** this doesn't run at all on 10.15 (big sur), arm/m1 machine:

- First run, got an OS popup: "fastbasic-int is damaged"
- Second and subsequent runs: one-line message,  `Killed: 9`

The `Killed: 9` message appears when I try to run any of the built executables: ar65, ca65, fastbasic-*, ld65.

Running the `fb` script therefore doesn't run either, with the same message:

```
Compiling 'test.bas' to assember 'test.asm'.
./fb: line 72: 27474 Killed: 9  "$FB" $OPTS "$PROG" "$ASM"
```

**Comment by dmsc** [comment]
Hi!

So, my cross development environment *can* compile for older Intel mac, but compiling for the newer ARM macs does not work. I should read more about the cross compiling tools.

I suppose that the AMD64 version also works (emulated) under the newer M1?

Thanks!

**Comment by billyc** [comment]
Hi again :-)

Yes, I should have added that!  The amd64 version works perfectly fine on the m1.

**Comment by billyc** [comment]
And to be clear: that's certainly sufficient, until your cross-dev environment is updated to work with m1. Don't sweat it.

**Comment by dmsc** [comment]
Ok, thanks!

I will replace the version available with a new one compiled with the new environment.

**Comment by dmsc** [comment]
Ok, I replaced the compiled binary.
