### ISSUE TITLE
Cross compiler overwrites files with different case on Windows.

### ISSUE THREAD

**Issue by PJM-NCC-70511** [dmsc/fastbasic#57]
I noticed the FastBasic.CFG (default) does not have anything to align a custom loaded font or assemble code directly to page 6. 
I managed to get it to align to fonts every 1K by adding      
"ALIGNFONT:load = MAIN,    type = ro,  optional = yes, define = yes, align = $400;" to SEGMENTS in the fastbasic config.

The other issue I am having is when I try to compile a program with an extra assembly, it is treating the "XMOVE.ASM" as an output file, and it will overwrite it if I do not mark it as read only. Luckily, I am able to restore it from a back up and update it again. I am trying to add some subroutines to move data to and from RAM under OS, or extended memory banks for Ataris with over 64K (130XE).

**Comment by dmsc** [comment]
Hi!

About your first question, yes, you need to add a new section to the config file if you want data placed at specific (or aligned) locations; then you can place data in your basic program using:
```
    DATA font() BYTEFILE [ALIGNFONT] "myfont.fnt"
```

This will include the contents of the file into the ALIGNFONT segment, note the section name limited by `[` and `]`.

For your second question, can you paste the command line you are using?

Have Fun!

**Comment by PJM-NCC-70511** [comment]
fb TGAtari\tg_edit.bas TGAtari\xmove.asm

I figured out what was going on, Originally, I had "XMOVE.ASM" and the file name having caps in the filename caused it to be treated as an output file for the compiler. May need to correct this because I had to rewrite my custom assembly code after the compiler overwrote the file.

**Comment by dmsc** [comment]
Fixed on repository. You can try with attached compiled version. [fastbasic-v4.6-fixed.57-win32.zip](https://github.com/dmsc/fastbasic/files/9793533/fastbasic-v4.6-fixed.57-win32.zip)
