### ISSUE TITLE
output minified listings

### ISSUE THREAD

**Issue by kimslawson** [dmsc/fastbasic#63]
A parser enhancement to minify fastbasic listings would be nice (ala [tbxlparser/basicparser](https://github.com/dmsc/tbxl-parser)). As @dmsc mentioned in a direct message, fastbasic currently provides the reverse functionality (expanding abbreviated listings). For the purposes of sizecoding it would be handy to automate the minification.

**Comment by dmsc** [comment]
This is planed, but not right now as it is not as easy to implement cleanly as it seems.
