### ISSUE TITLE
Editor in FB.COM: Bug when pressing Ctrl-DEL at end of sourcefile

### ISSUE THREAD

**Issue by std-xl** [dmsc/fastbasic#82]
After pressing Ctrl-DEL at end of last line, strange things happen when running the program:
E.g. type after starting FB.COM:

Ctrl-N ? 1 Ctrl-DEL Ctrl-R -> 1 1 is displayed

Ctrl-N A = 1 Return ? A Ctrl-DEL Ctrl-DEL Ctrl-R -> Parse Error

**Comment by dmsc** [comment]
Hi!

Thanks for the bug report.

When you press the DELETE key at the end of the line, the editor tries to join the line with the next - it needed a check to avoid deleting the last end of line.

Fixed now.
