### ISSUE TITLE
Question on virtual disk access

### ISSUE THREAD

**Issue by drarem** [dmsc/fastbasic#83]
When compiling an XEX file, is it possible to attach a 'virtual' ATR image so I only have to distribute a single .XEX?  I want to be able to save and load in this same space as well. This will keep it simple for any users from having to create a blank disk and attaching to the emulator on their own.

**Comment by dmsc** [comment]
Hi!

I don't completely understand your question.

Are you using the PC compiler?

Do you want to generate an ATR image with the Atari executable inside?

Have Fun!

**Comment by drarem** [comment]
Yes I'm using the PC compiler and created a large map using fastbasic. Want to be able to load/save or just integrate it directly into program. Able to generate and use the ATR image without having to manually create one would be ideal, but i would settle for even a bunch of DATA statements I can use for the program/game.

**Comment by dmsc** [comment]
Hi!

To integrate data directly to the program, you can use the DATA FILE statement:

```
  DATA mydata() BYTEFILE "my-local-file.bin"
```

This will read the binary file "my-local-file.bin" into your program, as the mydata() byte array. You can also use "WORDFILE" for reading as a word array.

Note that this does not work in the Atari compiler, only using the PC compiler.

Is this what you need?

Have Fun!

**Comment by drarem** [comment]
Hi. Was wanting to edit in the same program save it and reload it. Would i
need a D1 disk set up for an emulator to run it

**Comment by drarem** [comment]
When i get back to my desk tomorrow ill try to describe more.  I making a
game with built in map editor. I want to be able to make a map, save
it..exit  relaunch the game reload the msp to edit some more

**Comment by dmsc** [comment]
Hi!

I understand now, you want to test the game preserving the data in the disk image.

What I normally do is to activate the "H:" device in the emulator, and load/save the data from the H: device during development.

This way, I can load the emulator with my XEX and have it access all the data files in the H: device instantly, without the need for an ATR file. This also has the advantage that I can directly copy (and backup) the data files.

If you are using Altirra, you can load the emulator with ` Altirra /hdpathrw my_folder my_file.xex`

Have Fun!

**Comment by drarem** [comment]
Thank you  sounds like what i need to do

**Comment by dmsc** [comment]
Closing as seems resolved.
