### ISSUE TITLE
%TIME

### ISSUE THREAD

**Issue by mdraith** [dmsc/fastbasic#90]
`PRINT %TIME` does not work

**Comment by dmsc** [comment]
Hi!

You are probably trying an old version. `%TIME` is only available from pre-releases, you can download a test version from: https://github.com/dmsc/fastbasic/actions/runs/8963403908

Have Fun!

**Comment by mdraith** [comment]
I used the beta1 atr file on real hardware. Don't know how to get an atr file from your link.

**Comment by dmsc** [comment]
Here it is attached, in a ZIP file:

[fastbasic-atr.zip](https://github.com/user-attachments/files/16093104/fastbasic-atr.zip)

Have Fun!
