### ISSUE TITLE
ADD, SUB, MUL, DIV

### ISSUE THREAD

**Issue by mdraith** [dmsc/fastbasic#93]
Faster integer variable manipulation:

commands:
```
ADD A,3 for A=A+3
SUB A,3 for A=A-3
MUL A,3 for A=A*3
DIV A,3 for A=A/3
```

functions:
```
ADD(A,3) for A+3
SUB(A,3) for A-3
MUL(A,3) for A*3
DIV(A,3) for A/3
```

**Comment by dmsc** [comment]
Hi!

Thanks for your comments.

The proposed syntax won't be any faster that what the compiler currently produces - as it will generate the same code - and would be very unfriendly (it looks like assembly code).

Have Fun!
